-- GENERATED by scripts/build-seed.js. Do not edit by hand.
BEGIN;

INSERT INTO institutions ("id", "name", "short_name", "contact_email") VALUES
  ('INST-01', 'สจล. (KMITL)', 'KMITL', NULL),
  ('INST-02', 'มหาวิทยาลัย A', NULL, NULL),
  ('INST-03', 'มหาวิทยาลัย B', NULL, NULL),
  ('INST-04', 'มหาวิทยาลัย C', NULL, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO roles ("code", "name") VALUES
  ('exec', 'บริหาร'),
  ('marketing', 'ฝ่ายการตลาด'),
  ('gis', 'ผู้ดูแลข้อมูลสถานที่และอาคาร'),
  ('admin', 'ฝ่ายดูแลระบบ'),
  ('pr', 'ฝ่ายประชาสัมพันธ์'),
  ('registrar', 'ฝ่ายทะเบียน'),
  ('user', 'ผู้ใช้งานทั่วไป')
ON CONFLICT DO NOTHING;

INSERT INTO use_cases ("key", "title", "icon", "sort_order") VALUES
  ('overview', 'ดูรายงานและสถิติภาพรวมระบบ', 'svg:growth_graph', 0),
  ('feedback', 'ตรวจสอบข้อเสนอแนะและคำขอจากผู้ใช้งานทั่วไป', 'svg:Chat_search_light', 1),
  ('contracts', 'ตรวจสอบสัญญาที่ฝ่ายการตลาดทำกับฝ่ายการตลาด', 'svg:Folder_search_light', 2),
  ('audit', 'ตรวจสอบบันทึกประวัติการแก้ไขข้อมูลแผนที่', 'svg:Map_light', 3),
  ('broadcast', 'ส่งข้อความแจ้งเตือนระบบถึงมหาวิทยาลัยในระบบ', 'svg:bullhorn', 4),
  ('access', 'จัดการสิทธิ์การเข้าถึงระดับสถาบัน', 'svg:dataflow', 5),
  ('boundary', 'จัดการขอบเขตแผนผัง', '🗺️', 6),
  ('assets', 'จัดการข้อมูลประกอบแผนผัง', '🧩', 7),
  ('save', 'บันทึกข้อมูลแผนที่', '💾', 8),
  ('users', 'ข้อมูลผู้ใช้งาน', '👥', 9),
  ('requests', 'คำร้อง', '📋', 10),
  ('roles', 'สิทธิ์ผู้ใช้งาน', '🔑', 11),
  ('status', 'สถานะบัญชีผู้ใช้งาน', '🚦', 12),
  ('news', 'ข้อมูลข่าวสาร', 'svg:news', 13),
  ('events', 'ข้อมูลกิจกรรม', 'svg:bullhorn', 14),
  ('interest', 'ตรวจสอบสถิติความสนใจของกิจกรรม', 'svg:growth', 15),
  ('categories', 'เพิ่ม / แก้ไข / ลบหมวดหมู่กิจกรรมและสถานที่', 'svg:folder', 16),
  ('rooms', 'จัดการรายละเอียดข้อมูลบนแผนที่', '🗺️', 17),
  ('search', 'ค้นหาห้องเรียน อาคาร หรือชื่ออาจารย์', '🔍', 18),
  ('route', 'ค้นหาวิธีไปยังจุดหมาย', 'svg:compass', 19),
  ('common_1', 'ลงทะเบียนเข้าใช้ระบบ', NULL, 20),
  ('common_2', 'เข้าสู่ระบบด้วย E-mail', NULL, 21)
ON CONFLICT DO NOTHING;

INSERT INTO role_use_cases ("role_code", "use_case_key") VALUES
  ('exec', 'overview'),
  ('exec', 'feedback'),
  ('exec', 'contracts'),
  ('exec', 'audit'),
  ('marketing', 'contracts'),
  ('marketing', 'broadcast'),
  ('marketing', 'access'),
  ('gis', 'boundary'),
  ('gis', 'assets'),
  ('gis', 'save'),
  ('admin', 'users'),
  ('admin', 'requests'),
  ('admin', 'roles'),
  ('admin', 'status'),
  ('pr', 'news'),
  ('pr', 'events'),
  ('pr', 'interest'),
  ('pr', 'categories'),
  ('registrar', 'rooms'),
  ('registrar', 'requests'),
  ('user', 'search'),
  ('user', 'route'),
  ('user', 'feedback'),
  ('user', 'events'),
  ('exec', 'common_1'),
  ('marketing', 'common_1'),
  ('gis', 'common_1'),
  ('admin', 'common_1'),
  ('pr', 'common_1'),
  ('registrar', 'common_1'),
  ('user', 'common_1'),
  ('exec', 'common_2'),
  ('marketing', 'common_2'),
  ('gis', 'common_2'),
  ('admin', 'common_2'),
  ('pr', 'common_2'),
  ('registrar', 'common_2'),
  ('user', 'common_2')
ON CONFLICT DO NOTHING;

INSERT INTO users ("id", "email", "name", "username", "role_code", "institution_id", "status", "created_at", "password_hash") VALUES
  ('U001', 'exec@kmitl.ac.th', 'จินยอง ปาร์ค', 'exec', 'exec', 'INST-01', 'active', '2026-01-12', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U002', 'marketing@kmitl.ac.th', 'อาฮยาน จาง', 'marketing', 'marketing', 'INST-01', 'active', '2026-01-12', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U003', 'gis@kmitl.ac.th', 'ธานอส ซัง', 'gis', 'gis', 'INST-01', 'active', '2026-01-15', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U004', 'admin@kmitl.ac.th', 'แตงโม จัง', 'admin', 'admin', 'INST-01', 'active', '2026-01-10', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U005', 'pr@kmitl.ac.th', 'อาสะ คิม', 'pr', 'pr', 'INST-01', 'active', '2026-02-02', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U006', 'registrar@kmitl.ac.th', 'ฮง ไลเคน', 'registrar', 'registrar', 'INST-01', 'active', '2026-02-02', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U007', 'student@kmitl.ac.th', 'อินฟินิตี้ ไอ', 'student', 'user', 'INST-01', 'active', '2026-03-01', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6'),
  ('U008', 'somchai@kmitl.ac.th', 'สมชาย ตั้งมั่น', 'somchai', 'user', 'INST-01', 'active', '2026-03-04', '$2b$10$/I4qXknccgrR4piyV2Hz4ODGvEq5GpZbpfUAsTzCki1qAM9VWOzk6')
ON CONFLICT DO NOTHING;

INSERT INTO faculties ("id", "name") VALUES
  ('FAC-01', 'คณะวิศวกรรมศาสตร์'),
  ('FAC-02', 'คณะสถาปัตยกรรม ศิลปะและการออกแบบ'),
  ('FAC-03', 'คณะครุศาสตร์อุตสาหกรรมและเทคโนโลยี'),
  ('FAC-04', 'คณะเทคโนโลยีการเกษตร'),
  ('FAC-05', 'คณะวิทยาศาสตร์'),
  ('FAC-06', 'คณะเทคโนโลยีสารสนเทศ'),
  ('FAC-07', 'คณะอุตสาหกรรมอาหาร'),
  ('FAC-08', 'คณะบริหารธุรกิจ'),
  ('FAC-09', 'วิทยาลัยนวัตกรรมการผลิตขั้นสูง'),
  ('FAC-10', 'อื่น ๆ')
ON CONFLICT DO NOTHING;

INSERT INTO buildings ("id", "faculty_id", "code", "name", "outline", "bounds") VALUES
  ('BLD-SC8', 'FAC-05', 'SC8', 'Sc8', '[[13.729617,100.779691],[13.729617,100.780308],[13.728375,100.780315],[13.728375,100.780029],[13.728858,100.780029],[13.728858,100.779797],[13.729272,100.779797],[13.729272,100.779691]]'::jsonb, '[[13.728306,100.779664],[13.729686,100.780328]]'::jsonb),
  ('BLD-B001', 'FAC-05', 'B001', 'SC9', NULL, NULL),
  ('BLD-B002', 'FAC-05', 'B002', 'อาคารจุฬาภรณวลัยลักษณ์ 1', NULL, NULL),
  ('BLD-B003', 'FAC-05', 'B003', 'อาคารจุฬาภรณวลัยลักษณ์ 2', NULL, NULL),
  ('BLD-B004', 'FAC-01', 'B004', 'อาคาร 12 ชั้น', NULL, NULL),
  ('BLD-B005', 'FAC-01', 'B005', 'อาคารเรียนรวม', NULL, NULL),
  ('BLD-B006', 'FAC-01', 'B006', 'อาคารปฏิบัติการวิศวกรรม', NULL, NULL),
  ('BLD-B007', 'FAC-06', 'B007', 'อาคารคณะเทคโนโลยีสารสนเทศ', NULL, NULL),
  ('BLD-B008', 'FAC-10', 'B008', 'อาคารส่วนกลาง', NULL, NULL),
  ('BLD-B009', 'FAC-10', 'B009', 'พื้นที่ภายนอกอาคาร', NULL, NULL),
  ('BLD-B010', 'FAC-10', 'B010', 'อาคารสำนักงาน', NULL, NULL),
  ('BLD-B011', 'FAC-10', 'B011', 'อาคารกิจกรรมนักศึกษา', NULL, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO floors ("id", "building_id", "floor_no", "name", "svg", "note", "status") VALUES
  ('FL-SC8-8', 'BLD-SC8', '8', 'ชั้น 8', NULL, NULL, 'published'),
  ('FL-SC8-7', 'BLD-SC8', '7', 'ชั้น 7', NULL, NULL, 'published'),
  ('FL-SC8-6', 'BLD-SC8', '6', 'ชั้น 6', '/data/floorplans/Sc8/floor6.svg', NULL, 'published'),
  ('FL-SC8-5', 'BLD-SC8', '5', 'ชั้น 5', '/data/floorplans/Sc8/floor5.svg', NULL, 'published'),
  ('FL-SC8-4', 'BLD-SC8', '4', 'ชั้น 4', '/data/floorplans/Sc8/floor4.svg', NULL, 'published'),
  ('FL-SC8-3', 'BLD-SC8', '3', 'ชั้น 3', '/data/floorplans/Sc8/floor3.svg', NULL, 'published'),
  ('FL-SC8-2', 'BLD-SC8', '2', 'ชั้น 2', '/data/floorplans/Sc8/floor2.svg', NULL, 'published'),
  ('FL-SC8-1', 'BLD-SC8', '1', 'ชั้น 1', '/data/floorplans/Sc8/floor1.svg', NULL, 'published')
ON CONFLICT DO NOTHING;

INSERT INTO nodes ("id", "node_key", "floor_id", "name", "type", "x", "y") VALUES
  ('ND-0001', 'Sc8Lift1F1', 'FL-SC8-1', 'ลิฟต์ ชั้น1', 'lift', 100.7802095, 13.7291256),
  ('ND-0002', 'Sc8Toilet1F1', 'FL-SC8-1', 'ห้องน้ำชั้น 1', 'Toilet', 100.7800143, 13.7291665),
  ('ND-0003', 'Sc8FireExit1F1', 'FL-SC8-1', 'ทางหนึไฟชั้น 1', 'Fire_Exit', 100.7799855, 13.7288873),
  ('ND-0004', 'Sc8Entrance1F1', 'FL-SC8-1', 'ทางเข้าอาคารพระจอมชั้น 1', 'Entrance', 100.7799219, 13.7290372),
  ('ND-0005', 'Sc8Stair1F1', 'FL-SC8-1', 'ทางหนึไฟข้างลิฟต์ชั้น 1', 'Stair', 100.7801042, 13.7291831),
  ('ND-0006', 'Sc8Stair2F1', 'FL-SC8-1', 'บันไดกลางโถงชั้น 1', 'Stair', 100.7801518, 13.7290097),
  ('ND-0007', 'Sc8CoWork1F1', 'FL-SC8-1', 'coworking space KDAI', 'Co_Work', 100.7800338, 13.7288521),
  ('ND-0008', 'Sc8StudyRoom1F1', 'FL-SC8-1', 'ห้อง 108 ตึกพระจอมฯ', 'Study_Room', 100.7802591, 13.7291126),
  ('ND-0009', 'Sc8StudyRoom2F1', 'FL-SC8-1', 'ห้อง 107 ตึกพระจอมฯ', 'Study_Room', 100.7802711, 13.7289785),
  ('ND-0010', 'Sc8StudyRoom3F1', 'FL-SC8-1', 'ห้อง 106 ตึกพระจอมฯ', 'Study_Room', 100.7802738, 13.7288756),
  ('ND-0011', 'Sc8PC1', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800217, 13.7290345),
  ('ND-0012', 'Sc8PC2', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800928, 13.7290358),
  ('ND-0013', 'Sc8PC3', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7801504, 13.7290358),
  ('ND-0014', 'Sc8PC4', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.780023, 13.7290866),
  ('ND-0015', 'Sc8PC5', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800968, 13.7290879),
  ('ND-0016', 'Sc8PC6', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7801518, 13.7290853),
  ('ND-0017', 'Sc8PC7', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7801518, 13.7291296),
  ('ND-0018', 'Sc8PC8', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7801303, 13.7291556),
  ('ND-0019', 'Sc8PC9', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800131, 13.7291544),
  ('ND-0020', 'Sc8PC9_5', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800801, 13.729157),
  ('ND-0021', 'Sc8PC10', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800788, 13.7291818),
  ('ND-0022', 'Sc8PC11', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7802229, 13.7290853),
  ('ND-0023', 'Sc8PC12', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7802242, 13.7290345),
  ('ND-0024', 'Sc8PC13', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7802255, 13.7289798),
  ('ND-0025', 'Sc8PC14', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7802282, 13.7289212),
  ('ND-0026', 'Sc8PC15', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7802269, 13.7288769),
  ('ND-0027', 'Sc8PC16', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800847, 13.7288769),
  ('ND-0028', 'Sc8PC17', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800888, 13.7289811),
  ('ND-0029', 'Sc8PC18', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800834, 13.7289303),
  ('ND-0030', 'Sc8PC19', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800552, 13.7289016),
  ('ND-0031', 'Sc8PC20', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800123, 13.7288899),
  ('ND-0032', 'Sc8PC21', 'FL-SC8-1', 'ทางเดินอาคารพระจอมชั้น 1', 'path', 100.7800364, 13.728873),
  ('ND-0033', 'Sc8StudyRoom1CenterF1', 'FL-SC8-1', 'ห้อง 108 ตึกพระจอมฯ', 'path', 100.7802781, 13.7291617),
  ('ND-0034', 'Sc8StudyRoom2CenterF1', 'FL-SC8-1', 'ห้อง 107 ตึกพระจอมฯ', 'path', 100.7802956, 13.7289767),
  ('ND-0035', 'Sc8StudyRoom3CenterF1', 'FL-SC8-1', 'ห้อง 106 ตึกพระจอมฯ', 'path', 100.7803023, 13.728862),
  ('ND-0036', 'Sc8CoWork1F1Center', 'FL-SC8-1', 'coworking space KDAI', 'path', 100.7800917, 13.7288373),
  ('ND-0037', 'Sc8Ext0', 'FL-SC8-1', 'ทางเข้า Sc8', 'exterior', 100.7799681, 13.7290371)
ON CONFLICT DO NOTHING;

INSERT INTO edges ("id", "from_node_id", "to_node_id", "distance", "edge_type", "accessible") VALUES
  ('ED-0001', 'ND-0004', 'ND-0011', 10.8, 'walk', TRUE),
  ('ED-0002', 'ND-0011', 'ND-0012', 7.69, 'walk', TRUE),
  ('ED-0003', 'ND-0011', 'ND-0014', 5.76, 'walk', TRUE),
  ('ED-0004', 'ND-0014', 'ND-0015', 7.98, 'walk', TRUE),
  ('ED-0005', 'ND-0016', 'ND-0015', 5.95, 'walk', TRUE),
  ('ED-0006', 'ND-0012', 'ND-0013', 6.23, 'walk', TRUE),
  ('ED-0007', 'ND-0011', 'ND-0028', 9.35, 'walk', TRUE),
  ('ED-0008', 'ND-0012', 'ND-0015', 5.78, 'walk', TRUE),
  ('ED-0009', 'ND-0022', 'ND-0023', 5.62, 'walk', TRUE),
  ('ED-0010', 'ND-0013', 'ND-0016', 5.47, 'walk', TRUE),
  ('ED-0011', 'ND-0004', 'ND-0014', 12.22, 'walk', TRUE),
  ('ED-0012', 'ND-0016', 'ND-0017', 4.9, 'walk', TRUE),
  ('ED-0013', 'ND-0017', 'ND-0018', 3.7, 'walk', TRUE),
  ('ED-0014', 'ND-0018', 'ND-0019', 12.67, 'walk', TRUE),
  ('ED-0015', 'ND-0020', 'ND-0019', 7.25, 'walk', TRUE),
  ('ED-0016', 'ND-0019', 'ND-0002', 1.34, 'walk', TRUE),
  ('ED-0017', 'ND-0020', 'ND-0021', 2.74, 'walk', TRUE),
  ('ED-0018', 'ND-0021', 'ND-0005', 2.75, 'walk', TRUE),
  ('ED-0019', 'ND-0013', 'ND-0006', 2.89, 'walk', TRUE),
  ('ED-0020', 'ND-0016', 'ND-0001', 7.67, 'walk', TRUE),
  ('ED-0021', 'ND-0016', 'ND-0022', 7.69, 'walk', TRUE),
  ('ED-0022', 'ND-0022', 'ND-0008', 4.94, 'walk', TRUE),
  ('ED-0023', 'ND-0013', 'ND-0023', 7.98, 'walk', TRUE),
  ('ED-0024', 'ND-0023', 'ND-0024', 6.05, 'walk', TRUE),
  ('ED-0025', 'ND-0024', 'ND-0009', 4.93, 'walk', TRUE),
  ('ED-0026', 'ND-0024', 'ND-0025', 6.48, 'walk', TRUE),
  ('ED-0027', 'ND-0025', 'ND-0026', 4.9, 'walk', TRUE),
  ('ED-0028', 'ND-0026', 'ND-0010', 5.07, 'walk', TRUE),
  ('ED-0029', 'ND-0026', 'ND-0027', 15.38, 'walk', TRUE),
  ('ED-0030', 'ND-0027', 'ND-0032', 5.24, 'walk', TRUE),
  ('ED-0031', 'ND-0032', 'ND-0007', 2.33, 'walk', TRUE),
  ('ED-0032', 'ND-0032', 'ND-0031', 3.21, 'walk', TRUE),
  ('ED-0033', 'ND-0031', 'ND-0003', 2.91, 'walk', TRUE),
  ('ED-0034', 'ND-0012', 'ND-0028', 6.06, 'walk', TRUE),
  ('ED-0035', 'ND-0028', 'ND-0029', 5.65, 'walk', TRUE),
  ('ED-0036', 'ND-0029', 'ND-0030', 4.4, 'walk', TRUE),
  ('ED-0037', 'ND-0030', 'ND-0031', 4.82, 'walk', TRUE),
  ('ED-0038', 'ND-0030', 'ND-0032', 3.76, 'walk', TRUE),
  ('ED-0039', 'ND-0030', 'ND-0027', 4.2, 'walk', TRUE),
  ('ED-0040', 'ND-0004', 'ND-0037', 5, 'exterior', TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO categories ("id", "name", "kind", "color", "desc") VALUES
  ('CAT-01', 'วิชาการ', 'event', '#1A73E8', 'สัมมนา บรรยาย อบรม'),
  ('CAT-02', 'กีฬา/นันทนาการ', 'event', '#188038', 'กิจกรรมกีฬาและสันทนาการ'),
  ('CAT-03', 'อาคารเรียน', 'place', '#E37400', 'อาคารสำหรับการเรียนการสอน'),
  ('CAT-04', 'โรงอาหาร', 'place', '#D93025', 'จุดจำหน่ายอาหารและเครื่องดื่ม'),
  ('CAT-05', 'ลานกิจกรรม', 'place', '#8430CE', 'พื้นที่โล่งสำหรับจัดกิจกรรม')
ON CONFLICT DO NOTHING;

INSERT INTO rooms ("id", "code", "name", "type", "capacity", "teacher", "node_id", "category_id", "floor_id") VALUES
  ('RM-01', '106', 'ห้อง 106', 'ห้องเรียน', 45, 'อ.ดร. ปรีชา วงศ์ทอง', 'ND-0010', 'CAT-03', 'FL-SC8-1'),
  ('RM-02', '107', 'ห้อง 107', 'ห้องปฏิบัติการ', 40, 'อ.ดร. สุนิสา ภูผา', 'ND-0009', 'CAT-03', 'FL-SC8-1'),
  ('RM-03', 'KDAI', 'Coworking Space KDAI', 'พื้นที่ทำงานร่วม', 60, '-', 'ND-0007', 'CAT-03', 'FL-SC8-1'),
  ('RM-04', '108', 'ห้อง 108', 'ห้องเรียน', 45, 'อ.ดร. มานพ ศรีสุข', 'ND-0008', 'CAT-03', 'FL-SC8-1')
ON CONFLICT DO NOTHING;

INSERT INTO map_boundaries ("id", "building_id", "name", "type", "geometry", "status", "updated_at") VALUES
  ('MB-01', NULL, 'ขอบเขตวิทยาเขตลาดกระบัง', 'campus', NULL, 'published', '2026-08-01'),
  ('MB-02', 'BLD-SC8', 'ขอบเขตอาคารพระจอมเกล้าฯ (Sc8)', 'building', NULL, 'published', '2026-08-20')
ON CONFLICT DO NOTHING;

INSERT INTO map_assets ("id", "floor_id", "name", "kind", "file", "status", "updated_at") VALUES
  ('MA-01', 'FL-SC8-1', 'ผังชั้น 1 อาคาร Sc8', 'floorplan', '/data/floorplans/Sc8/floor1.svg', 'published', '2026-08-06'),
  ('MA-02', 'FL-SC8-2', 'ผังชั้น 2 อาคาร Sc8', 'floorplan', '/data/floorplans/Sc8/floor2.svg', 'published', '2026-08-06'),
  ('MA-03', NULL, 'ภาพอาคาร Sc8', 'image', '/data/places/sc8.png', 'published', '2026-07-28')
ON CONFLICT DO NOTHING;

INSERT INTO map_drafts ("id", "building_id", "saved_by", "name", "note", "status", "saved_at") VALUES
  ('MD-01', 'BLD-SC8', 'U003', 'ปรับพิกัดทางเข้าอาคาร Sc8', 'ย้ายจุดทางเข้าฝั่งเหนือ 3 เมตร', 'draft', '2026-08-22T11:15:00+07:00')
ON CONFLICT DO NOTHING;

INSERT INTO request_quota ("id", "per_user_per_day", "per_user_per_month", "updated_at", "updated_by") VALUES
  ('RQ-CONF', 3, 20, '2026-09-22', 'U004')
ON CONFLICT DO NOTHING;

INSERT INTO requests ("id", "user_id", "subject", "detail", "status", "created_at", "note", "room_id", "node_id", "before", "after") VALUES
  ('RQ-1001', 'U007', 'ขอแก้ไขข้อมูลห้อง 106', 'ขอเปลี่ยนประเภทห้อง 106 จากห้องเรียนเป็นห้องปฏิบัติการ', 'pending', '2026-08-24', '', 'RM-01', 'ND-0010', '{"name":"ห้อง 106","type":"ห้องเรียน","capacity":45,"teacher":"อ.ดร. ปรีชา วงศ์ทอง"}', '{"name":"ห้อง 106","type":"ห้องปฏิบัติการ","capacity":45,"teacher":"อ.ดร. ปรีชา วงศ์ทอง"}'),
  ('RQ-1002', 'U007', 'แจ้งข้อมูลอาจารย์ประจำห้อง 107 ไม่ถูกต้อง', 'ชื่ออาจารย์ประจำห้อง 107 ไม่ตรงกับข้อมูลที่แสดงในระบบ', 'pending', '2026-08-24', '', 'RM-02', 'ND-0009', '{"name":"ห้อง 107","type":"ห้องปฏิบัติการ","capacity":40,"teacher":"อ.ดร. สุนิสา ภูผา"}', '{"name":"ห้อง 107","type":"ห้องปฏิบัติการ","capacity":40,"teacher":"อ.ดร. วิชัย ใจดี"}'),
  ('RQ-1003', 'U008', 'แจ้งข้อมูลความจุ Coworking Space KDAI', 'ขอให้ตรวจสอบจำนวนที่นั่งของ Coworking Space KDAI', 'pending', '2026-08-24', '', 'RM-03', 'ND-0007', '{"name":"Coworking Space KDAI","type":"พื้นที่ทำงานร่วม","capacity":60,"teacher":"-"}', '{"name":"Coworking Space KDAI","type":"พื้นที่ทำงานร่วม","capacity":70,"teacher":"-"}')
ON CONFLICT DO NOTHING;

INSERT INTO broadcasts ("id", "sent_by", "title", "body", "audience", "send_at") VALUES
  ('BC-01', 'U002', 'แจ้งปิดปรับปรุงระบบ', 'ระบบจะปิดปรับปรุง 30 ส.ค. 2026 เวลา 01:00–03:00 น.', 'ทุกมหาวิทยาลัย', '2026-08-15T10:00:00+07:00'),
  ('BC-02', 'U002', 'แจ้งกำหนดการบำรุงรักษาเซิร์ฟเวอร์', 'ระบบแผนที่จะไม่สามารถใช้งานได้ชั่วคราวในคืนวันที่กำหนด', 'ทุกมหาวิทยาลัย', '2026-09-10T08:00:00+07:00')
ON CONFLICT DO NOTHING;

INSERT INTO notifications ("id", "user_id", "broadcast_id", "kind", "title", "body", "read", "created_at") VALUES
  ('NT-001', 'U008', NULL, 'account', 'บัญชีถูกระงับ', 'บัญชีของคุณถูกระงับการใช้งาน กรุณาติดต่อผู้ดูแลระบบ', FALSE, '2026-08-26')
ON CONFLICT DO NOTHING;

INSERT INTO feedback ("id", "user_id", "topic", "detail", "status", "created_at", "reply") VALUES
  ('FB-2001', 'U007', 'การใช้งานแผนที่', 'อยากให้ค้นหาด้วยรหัสวิชาได้', 'new', '2026-08-19', ''),
  ('FB-2002', 'U008', 'ปัญหาการใช้ระบบ', 'กดค้นหาห้องน้ำแล้วหมุดไม่ขึ้น', 'reviewed', '2026-08-12', 'แก้ไขแล้วในเวอร์ชัน 1.2.3')
ON CONFLICT DO NOTHING;

INSERT INTO news ("id", "title", "body", "publish_at", "expire_at", "published", "created_at", "author_id") VALUES
  ('NW-01', 'ประกาศตารางสอบกลางภาค 1/2569', 'นักศึกษาสามารถตรวจสอบตารางสอบกลางภาคได้ที่ระบบทะเบียน ตั้งแต่วันที่ประกาศเป็นต้นไป', '2026-08-20', '2026-09-30', TRUE, '2026-08-18', 'U005'),
  ('NW-02', 'เปิดรับสมัครทุนการศึกษา ประจำปี 2569', 'เปิดรับสมัครทุนการศึกษาสำหรับนักศึกษาชั้นปีที่ 2 ขึ้นไป ยื่นเอกสารได้ที่งานกิจการนักศึกษา', '2026-09-01', '2026-10-15', TRUE, '2026-08-22', 'U005'),
  ('NW-03', 'แจ้งปิดปรับปรุงลิฟต์อาคาร Sc8', 'ลิฟต์ฝั่งทิศเหนือปิดปรับปรุงชั่วคราว ขออภัยในความไม่สะดวก', '2026-07-01', '2026-07-31', TRUE, '2026-06-28', 'U005'),
  ('NW-04', 'ร่าง: กำหนดการปฐมนิเทศนักศึกษาใหม่', 'อยู่ระหว่างรอยืนยันกำหนดการจากคณะ', NULL, NULL, FALSE, '2026-08-23', 'U005')
ON CONFLICT DO NOTHING;

INSERT INTO events ("id", "name", "detail", "category_id", "start_at", "end_at", "place_name", "lat", "lon", "temp_place_category_id", "published", "created_at", "author_id") VALUES
  ('EV-01', 'ISE Open House 2026', 'เปิดบ้านคณะวิศวกรรมศาสตร์นานาชาติ พบกิจกรรมและ workshop ตลอดวัน', 'CAT-01', '2026-09-05T09:00', '2026-09-05T16:00', 'ลานหน้าอาคารพระจอมเกล้าฯ (Sc8)', 13.729721, 100.780099, 'CAT-05', TRUE, '2026-08-10', 'U005'),
  ('EV-02', 'กีฬาสีภาควิชา', 'แข่งขันกีฬาสีประจำปี ณ สนามกีฬากลาง', 'CAT-02', '2026-09-18T08:00', '2026-09-19T17:00', 'สนามกีฬากลาง สจล.', 13.7275, 100.7772, NULL, TRUE, '2026-08-12', 'U005'),
  ('EV-03', 'อบรมการใช้งาน SciMap', 'อบรมการใช้งานระบบแผนที่สำหรับเจ้าหน้าที่ภาควิชา', 'CAT-01', '2026-08-01T13:00', '2026-08-01T16:00', 'Coworking Space KDAI', 13.729, 100.7799, NULL, TRUE, '2026-07-20', 'U005')
ON CONFLICT DO NOTHING;

INSERT INTO event_interest ("event_id", "user_id", "created_at") VALUES
  ('EV-01', 'U007', '2026-08-20')
ON CONFLICT DO NOTHING;

INSERT INTO event_stats ("event_id", "searched") VALUES
  ('EV-01', 402),
  ('EV-02', 88),
  ('EV-03', 51)
ON CONFLICT DO NOTHING;

INSERT INTO contracts ("id", "plan", "start_date", "end_date", "status", "contact", "institution_id") VALUES
  ('CT-01', 'Campus Pro', '2025-09-01', '2026-08-31', 'active', 'ict@kmitl.ac.th', 'INST-01'),
  ('CT-02', 'Campus Basic', '2025-06-01', '2026-09-15', 'active', 'it@univ-a.ac.th', 'INST-02'),
  ('CT-03', 'Campus Pro', '2024-10-01', '2026-08-26', 'active', 'admin@univ-b.ac.th', 'INST-03'),
  ('CT-04', 'Trial', '2026-05-01', '2026-07-31', 'expired', 'office@univ-c.ac.th', 'INST-04')
ON CONFLICT DO NOTHING;

INSERT INTO modules ("code", "name") VALUES
  ('map', 'แผนที่'),
  ('events', 'กิจกรรม'),
  ('rooms', 'ข้อมูลห้อง'),
  ('reports', 'รายงาน')
ON CONFLICT DO NOTHING;

INSERT INTO institution_access ("id", "level", "seats", "access_status", "updated_at", "institution_id") VALUES
  ('IA-01', 'full', 5000, 'active', '2026-07-01', 'INST-01'),
  ('IA-02', 'standard', 2000, 'active', '2026-06-11', 'INST-02'),
  ('IA-03', 'full', 3500, 'active', '2026-05-20', 'INST-03'),
  ('IA-04', 'readonly', 300, 'active', '2026-05-01', 'INST-04')
ON CONFLICT DO NOTHING;

INSERT INTO institution_access_modules ("access_id", "module_code") VALUES
  ('IA-01', 'map'),
  ('IA-01', 'events'),
  ('IA-01', 'rooms'),
  ('IA-01', 'reports'),
  ('IA-02', 'map'),
  ('IA-02', 'events'),
  ('IA-03', 'map'),
  ('IA-03', 'events'),
  ('IA-03', 'rooms'),
  ('IA-04', 'map')
ON CONFLICT DO NOTHING;

INSERT INTO access_history ("id", "access_id", "actor_id", "before_status", "after_status", "changed_at") VALUES
  ('AH-001', 'IA-04', 'U002', 'active', 'suspended', '2026-08-20T10:00:00+07:00')
ON CONFLICT DO NOTHING;

INSERT INTO edit_logs ("id", "user_id", "action", "before", "after", "edited_at", "map_boundary_id", "target_label", "room_id", "event_id") VALUES
  ('ML-3001', 'U003', 'แก้ไขขอบเขตแผนผัง', 'polygon v2', 'polygon v3', '2026-08-20T14:02:00+07:00', 'MB-02', 'ขอบเขตอาคารพระจอมเกล้าฯ (Sc8)', NULL, NULL),
  ('ML-3002', 'U006', 'แก้ไขข้อมูลห้อง', 'ห้องเรียนรวม', 'ห้องปฏิบัติการ', '2026-08-19T09:41:00+07:00', NULL, 'ห้อง 107 ชั้น 1', 'RM-02', NULL),
  ('ML-3003', 'U005', 'เพิ่มตำแหน่งกิจกรรม', '-', 'ลานหน้าอาคาร Sc8', '2026-08-17T16:20:00+07:00', NULL, 'ISE Open House 2026', NULL, 'EV-01')
ON CONFLICT DO NOTHING;

INSERT INTO usage ("month", "active_users", "searches", "routes") VALUES
  ('2026-03', 1820, 9120, 4310),
  ('2026-04', 2110, 10480, 5020),
  ('2026-05', 2450, 12240, 6110),
  ('2026-06', 1980, 8830, 3990),
  ('2026-07', 2680, 13910, 6840),
  ('2026-08', 3120, 16240, 7930)
ON CONFLICT DO NOTHING;

COMMIT;
