const fs = require('fs');
const path = require('path');
const { createRequire } = require('module');
const root = path.resolve(__dirname, '..');
const backendRequire = createRequire(path.join(root, 'backend', 'package.json'));
let bcrypt;
try { bcrypt = backendRequire('bcryptjs'); } catch { console.error('Missing bcryptjs. Run: cd backend && npm install'); process.exit(1); }
const dir = path.join(root, 'db', 'seed');
const out = path.join(root, 'db', 'seed.sql');
const camelToSnake = s => s.replace(/[A-Z]/g, c => '_' + c.toLowerCase());
const esc = s => String(s).replace(/'/g, "''");
function sqlValue(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'object') return `'${esc(JSON.stringify(v))}'::jsonb`;
  return `'${esc(v)}'`;
}
const order = [
  'institutions','roles','use_cases','role_use_cases','users','account_history',
  'faculties','buildings','floors','nodes','edges','categories','rooms',
  'map_boundaries','map_assets','map_drafts','request_quota','requests',
  'broadcasts','notifications','feedback','news','events','event_interest','event_stats',
  'contracts','modules','institution_access','institution_access_modules','access_history','edit_logs','usage'
];
const seedPasswordHash = bcrypt.hashSync('1234', 10);
const lines = ['-- GENERATED by scripts/build-seed.js. Do not edit by hand.','BEGIN;'];
for (const table of order) {
  const file = path.join(dir, table + '.json');
  if (!fs.existsSync(file)) continue;
  let rows = JSON.parse(fs.readFileSync(file, 'utf8'));
  if (!Array.isArray(rows)) rows = [rows];
  if (!rows.length) continue;
  rows = rows.map(r => {
    const x = {...r};
    if (table === 'users') {
      x.passwordHash = seedPasswordHash;
    }
    return x;
  });
  const cols = [...new Set(rows.flatMap(r => Object.keys(r)))];
  lines.push(`\nINSERT INTO ${table} (${cols.map(c=>`"${camelToSnake(c)}"`).join(', ')}) VALUES`);
  lines.push(rows.map(r => '  (' + cols.map(c => sqlValue(r[c])).join(', ') + ')').join(',\n') + '\nON CONFLICT DO NOTHING;');
}
lines.push('\nCOMMIT;','');
fs.writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out}`);
